FROM jupyter/base-notebook

RUN conda install voila ipywidgets pandas ipympl matplotlib
RUN pip install ipydeps ipython_blocking

#RUN jupyter nbextension install --user --py voila
#RUN jupyter nbextension enable --user --py voila
