name: voila
channels:
  - conda-forge
dependencies:
  - ipyleaflet
  - ipympl
  - ipywidgets
  - matplotlib
  - pandas
  - panel
  - papermill
  - voila=0.2
  - pip
  - pip:
    - ipydeps
    - ipython_blocking
    - qgrid
