name: voila
channels:
  - conda-forge
dependencies:
  - ipyleaflet
  - ipympl
  - ipywidgets
  - matplotlib
  - pandas
  - panel
  - qgrid
  - voila
  - pip
  - pip:
    - ipydeps
    - ipython_blocking
